config/routes.rb
Rails.application.routes.draw do
  resources :homes
  devise_for :users
  root "pages#home"
  get "about" => "pages#about"
  get 'search', to: 'search#search'

end

app/models/home.rb
#Added for ElasticSearch
require 'elasticsearch/model'

class Home < ActiveRecord::Base
	include Elasticsearch::Model
	include Elasticsearch::Model::Callbacks
	
	belongs_to :user
	has_attached_file :image, :styles => { :medium => "600x400>", :thumb => "150x100>" }
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

end

Home.import # for auto sync model with elastic search

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :homes	   
  
  #validates :name, presence: true               
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :configure_permitted_parameters, if: :devise_controller?
protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :name
   devise_parameter_sanitizer.for(:account_update) << :name
 end  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @homes = Home.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 3)
  end

  def show
  end

  def new
    @home = current_user.homes.build
  end

  def edit
  end

  def create
    @home = current_user.homes.build(home_params)
	if @home.save
		redirect_to @home, notice: 'Home was successfully created.'
	else
		render action: 'new'
	end
  end

  def update
	if @home.update(home_params)
		redirect_to @home, notice: 'Home was successfully updated.'
	else
		render action: 'edit'
	end
  end

  def destroy
    @home.destroy
	redirect_to homes_url, notice: 'Home was successfully deleted.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find_by(id: params[:id])
      #redirect_to homes_path, notice: "Not authorized to edit this Home" if @home.nil?
    end

    def correct_user
      @pin = current_user.homes.find_by(id: params[:id])
      redirect_to homes_path, notice: "Not authorized to edit this Home" if @home.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
		params.require(:home).permit(:name, :address1, :city, :postalCode, :province, :country, :description, :image)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
	def search
	  if params[:q].nil?
	    @homes = []
	  else
	    @homes = Home.search params[:q]
	  end
	end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/homes/_form.html.erb
<%= form_for @home, html: { multipart: true } do |f| %>
  <% if @home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% @home.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address1 %><br>
    <%= f.text_field :address1 %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :postalCode %><br>
    <%= f.text_field :postalCode %>
  </div>
  <div class="field">
    <%= f.label :province %><br>
    <%= f.text_field :province %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/homes/edit.html.erb
<h1>Editing Home</h1>

<%= render 'form' %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/index.html.erb
	<div class="row">
		<div class="col-xs-3">
			<div class="well">
				<h4 style="margin-top:0;">Quick Search</h4>
				<br/>
				<form>
				  <div class="form-group">
				    <label for="keyword">Keyword</label>
				    <input type="email" class="form-control" id="keyword" placeholder="Keyword">
				  </div>
				  
				  <div class="form-group">
					  <label for="city">City</label>
					  <select class="form-control" id="city">
						  <option>City 1</option>
						  <option>City 2</option>
						  <option>City 3</option>
						  <option>City 4</option>
						  <option>City 5</option>
						</select>
				  </div>
				
				  
				  <button type="submit" class="btn btn-primary">Submit</button>
				</form>				
			</div>
		</div>
		<div class="col-xs-9">
			
			<p id="notice"><%= notice %></p>
			
			
			<% @homes.each do |home| %>
				<div class="well">
					<div class="row">
					  <div class="col-xs-3">
						  <%= link_to image_tag(home.image.url(:medium)), home %>
						 <!--<%= image_tag home.image.url(:medium) %>-->
					  </div>
					  <div class="col-xs-9">
							<h2 style="margin-top:0;"><%= home.name %></h2>
					        <p><%= home.address1 %>, <%= home.city %>, <%= home.province %></p>
					        
					        <%= link_to 'Show', home, class: "btn btn-info" %>
							<% if home.user == current_user %>
								<%= link_to 'Edit', edit_home_path(home), class: "btn btn-default" %>
								<%= link_to 'Destroy', home, method: :delete, data: { confirm: 'Are you sure?' } %>
							<% end %>
					  </div>
					</div>
				</div>
			 <% end %>
			
			<br>
			
			<% if user_signed_in? %>
			  <%= link_to 'New Home', new_home_path, class: "btn btn-primary" %>
			<% end %>
		</div>
	</div>
	
	
	<div class="center"> <%= will_paginate @homes, renderer: BootstrapPagination::Rails %> </div>

app/views/homes/new.html.erb
<h1>New Home</h1>

<%= render 'form' %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @home.image.url %>

<p>
  <strong>Name:</strong>
  <%= @home.name %>
</p>

<p>
  <strong>Address1:</strong>
  <%= @home.address1 %>
</p>

<p>
  <strong>City:</strong>
  <%= @home.city %>
</p>

<p>
  <strong>Postalcode:</strong>
  <%= @home.postalCode %>
</p>

<p>
  <strong>Province:</strong>
  <%= @home.province %>
</p>

<p>
  <strong>Country:</strong>
  <%= @home.country %>
</p>

<p>
  <strong>Description:</strong>
  <%= @home.description %>
</p>

<% if @home.user == current_user %>
  <%= link_to 'Edit', edit_home_path(@home) %>
<% end %>
<%= link_to 'Back', homes_path %>

app/views/layouts/_header.html.erb
	<nav class="navbar navbar-default" role="navigation">
	  <div class="container">
	  <!-- Brand and toggle get grouped for better mobile display -->
	  <div class="navbar-header">
	    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
	      <span class="sr-only">Toggle navigation</span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	    </button>
	    
	    <%= link_to "Directory", root_path, class: "navbar-brand" %>
	  </div>
	
	  <!-- Collect the nav links, forms, and other content for toggling -->
	  <div class="collapse navbar-collapse navbar-ex1-collapse">
	    <ul class="nav navbar-nav navbar-right">
	      <li><%= link_to "Home", root_path %></li>
	      <li><%= link_to "About", about_path %></li> 
	      
	      <% if user_signed_in? %>
	      	<li><%= link_to "Account Settings", edit_user_registration_path %></li>
          	<li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
		  <% else %>
          	<li><%= link_to "Sign in", new_user_session_path %></li>
		  <% end %>
	      
	    </ul>
	  </div><!-- /.navbar-collapse -->
	  </div>
	</nav>	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Epdirectory</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<%= render 'layouts/header' %>

<div class="container">
	<% flash.each do |name, msg| %>
	     <%= content_tag(:div, msg, class: "alert alert-info") %>
	<% end %>
	
	<%= yield %>
</div>


</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<p>Etiam porta sem malesuada magna mollis euismod. Nulla vitae elit libero, a pharetra augue. Nulla vitae elit libero, a pharetra augue. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Maecenas sed diam eget risus varius blandit sit amet non magna.</p>

app/views/pages/home.html.erb
<div class="row">
	<div class="col-md-12">
		<ul>
			<li>
				<%= link_to 'Homes', homes_path %>
			</li>
			
		</ul>
	</div>
</div>	

app/views/search/search.html.erb
<h1>Homes Search</h1>
 
<%= form_for search_path, method: :get do |f| %>
  <p>
    <%= f.label "Search for" %>
    <%= text_field_tag :q, params[:q] %>
    <%= submit_tag "Go", name: nil %>
  </p>
<% end %>
 
<ul>
  <% @homes.each do |home| %>
    <li>
      <h3>
        <%= link_to home.name, controller: "homes", action: "show", id: home._id%>
      </h3>
    </li>
  <% end %>
</ul>